CREATE TABLE clientes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255)                            NOT NULL,
    cpf         VARCHAR(14)                             NOT NULL,
    genero      VARCHAR(20)                             NOT NULL,
    telefone    VARCHAR(20)                             NOT NULL,
    email       VARCHAR(100),
    logradouro  VARCHAR(50)                             NOT NULL,
    bairro      VARCHAR(50)                             NOT NULL,
    cep         VARCHAR(8)                              NOT NULL,
    numero      INTEGER                                 NOT NULL,
    complemento VARCHAR(255),
    cidade      VARCHAR(50)                             NOT NULL,
    uf          VARCHAR(2)                              NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (id)
);

CREATE TABLE contas
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id      BIGINT                                  NOT NULL,
    saldo           DECIMAL(10),
    tipo_conta      VARCHAR(30)                             NOT NULL,
    data_de_criacao TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    esta_ativa      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_contas PRIMARY KEY (id)
);

ALTER TABLE clientes
    ADD CONSTRAINT uc_clientes_cpf UNIQUE (cpf);

ALTER TABLE contas
    ADD CONSTRAINT FK_CONTAS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (id);